post_folder: posts
post_pinned_folder: posts/pinned

color_palette:
  red: de2c3b
  blue: 2575ed
  yellow: ffc800
  green: 2c9f42
  purple: 8156a7

tag_color:
  tools: purple
  projects: red
  events: yellow
  games: green
  songs: green
  shows: green
  ideas: blue
